# Generated by Django 2.2.7 on 2019-11-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeM',
            fields=[
                ('nombre', models.CharField(max_length=30)),
                ('id_anime', models.AutoField(primary_key=True, serialize=False)),
                ('image_anime', models.ImageField(blank=True, null=True, upload_to='anime/%Y/%m/$d/')),
                ('descripcion', models.CharField(max_length=300)),
            ],
        ),
    ]
