# Generated by Django 2.2.1 on 2019-05-21 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductosM',
            fields=[
                ('nombre', models.CharField(max_length=30)),
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('image_producto', models.ImageField(blank=True, null=True, upload_to='producto/%Y/%m/$d/')),
                ('precio', models.PositiveIntegerField()),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
    ]
