# Generated by Django 2.2.1 on 2019-05-22 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listacompra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productosm',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
    ]
