# Generated by Django 2.2.1 on 2019-05-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listacompra', '0004_auto_20190521_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productosm',
            name='descripcion',
            field=models.URLField(max_length=500),
        ),
    ]
